<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(

    'zend-skeleton-module/skeleton/foo'   => __DIR__ . '/view/zend-skeleton-module/skeleton/foo.phtml',
    'zend-skeleton-module/skeleton/index' => __DIR__ . '/view/zend-skeleton-module/skeleton/index.phtml',
);
