<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                            => __DIR__ . '/Module.php',
    'Application\Controller\IndexController'        => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Form\Fieldset\InputFilterFieldset' => __DIR__ . '/src/Application/Form/Fieldset/InputFilterFieldset.php',
    'Application\Module\AbstractModule'             => __DIR__ . '/src/Application/Module/AbstractModule.php',
    'Application\Utils\UuidGenerator'               => __DIR__ . '/src/Application/Utils/UuidGenerator.php',
);
