<?php echo $this->doctype(); ?>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <!--title>OneWaySkins</title-->
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>


    <!-- Bootstrap core CSS -->
    <!--link href="css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="css/style.css"-->

    <!-- Custom styles for this template -->
    <!--link href="blog.css" rel="stylesheet"-->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<header>
    <div class="backgroundHeader">

    </div>
    <!-- Menu -->
    <div class="topLoneMenu">
        <div class="container">
            <div class="row">
                <div class="col-md-5">
                    <div class="menuElements menuElementsFirst">
                        <ul>
                            <li><a href="#">Содержимое ботов</a></li>
                            <li><a href="#">Кейсы</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-2 logoContCol">
                    <div class="logoCont">
                        <a href="/">
                            <img src="images/logo.png">
                            <span>onewayskins.ru</span>
                        </a>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="menuElements menuElementsSecond">
                        <ul>
                            <li><a href="#">Акции</a></li>
                            <li><a href="#">Отзывы</a></li>
                        </ul>
                    </div>
                    <div class="enterTheSteamCont">
                        <div class="steamElement">
                            <div class="steamImg">
                                <img src="images/steamLogo.png">
                            </div>
                            <div class="steamLink">
                                <a id="steamAuthLink" href="#"><span>Войти через<br>steam-аккаунт</span></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Слайдер -->
    <div class="sliderTop">
        <div class="container">
            <div class="col-md-6 col-md-offset-6">
                <div class="titleSlider">
                    <h1>Магазин кейсов CS:GO</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- Слайдер -->

</header>
<!-- Полоса побед -->
<section class="onlineWinnerLine">
    <div class="container">
        <div class="col-md-2">
            <div class="elementOnlineContainer">
                <img src="images/ironIcon.png">
            </div>
        </div>
        <div class="col-md-10">
            <div class="rowsetElementsOnlineWin">
                <div class="winElement">
                    <div class="imgWinContent">
                        <img class="img-responsive" src="images/125fx125(1).png">
                    </div>
                    <div class="userWinName">
                        <span>=N@GIB@T0R2004=</span>
                    </div>
                </div>

                <div class="winElement">
                    <div class="imgWinContent">
                        <img class="img-responsive" src="images/125fx125(2).png">
                    </div>
                    <div class="userWinName">
                        <span>=N@GIB@T0R2004=</span>
                    </div>
                </div>

                <div class="winElement">
                    <div class="imgWinContent">
                        <img class="img-responsive" src="images/125fx125(3).png">
                    </div>
                    <div class="userWinName">
                        <span>=N@GIB@T0R2004=</span>
                    </div>
                </div>

                <div class="winElement">
                    <div class="imgWinContent">
                        <img class="img-responsive" src="images/125fx125(4).png">
                    </div>
                    <div class="userWinName">
                        <span>=N@GIB@T0R2004=</span>
                    </div>
                </div>

                <div class="winElement">
                    <div class="imgWinContent">
                        <img class="img-responsive" src="images/125fx125(5).png">
                    </div>
                    <div class="userWinName">
                        <span>=N@GIB@T0R2004=</span>
                    </div>
                </div>

                <div class="winElement">
                    <div class="imgWinContent">
                        <img class="img-responsive" src="images/125fx125(6).png">
                    </div>
                    <div class="userWinName">
                        <span>=N@GIB@T0R2004=</span>
                    </div>
                </div>

                <div class="winElement">
                    <div class="imgWinContent">
                        <img class="img-responsive" src="images/125fx125(7).png">
                    </div>
                    <div class="userWinName">
                        <span>=N@GIB@T0R2004=</span>
                    </div>
                </div>

                <div class="winElement">
                    <div class="imgWinContent">
                        <img class="img-responsive" src="images/125fx125.png">
                    </div>
                    <div class="userWinName">
                        <span>=N@GIB@T0R2004=</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Полоса побед -->
<!-- Главная секция -->
<section class="mainContent">

    <?=$this->content;?>

    <div class="topH2line">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2>Топ 6</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="topCasesContainer">

    </div>

    <div class="maxSaleH2line">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2>Максимальный скидон</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="salesCasesContainer">

    </div>

    <div class="freshH2line">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2>Свежак</h2>
                </div>
            </div>
        </div>
    </div>
    <div class="newCasesContainer">

    </div>

</section>
<!-- Главная секция -->
<!-- Футер -->
<footer class="blog-footer">
    <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
</footer>
<!-- Футер -->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<!-- Scripts -->
<?php echo $this->headScript()
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath("https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"))
    ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
; ?>

</body>
</html>
