<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Users\Module'                              => __DIR__ . '/Module.php',
    'Users\Controller\IndexController'          => __DIR__ . '/src/Controller/IndexController.php',
    'Users\Controller\IndexControllerFactory'   => __DIR__ . '/src/Controller/IndexControllerFactory.php',
    'Users\Entity\AbstractUsers'                => __DIR__ . '/src/Entity/AbstractUsers.php',
    'Users\Entity\Users'                        => __DIR__ . '/src/Entity/Users.php',
    'Users\Entity\UsersRepository'              => __DIR__ . '/src/Entity/UsersRepository.php',
    'Users\Form\Fieldset\UsersFieldset'         => __DIR__ . '/src/Form/Fieldset/UsersFieldset.php',
    'Users\Form\UsersForm'                      => __DIR__ . '/src/Form/UsersForm.php',
    'Users\Service\OpenidService'               => __DIR__ . '/src/Service/OpenidService.php',
    'Users\Service\UsersService'                => __DIR__ . '/src/Service/UsersService.php',
    'Users\Service\UsersServiceFactory'         => __DIR__ . '/src/Service/UsersServiceFactory.php',
    'ZendSkeletonModuleTest\Framework\TestCase' => __DIR__ . '/tests/ZendSkeletonModule/Framework/TestCase.php',
    'ZendSkeletonModuleTest\SampleTest'         => __DIR__ . '/tests/ZendSkeletonModule/SampleTest.php',
);
