<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Users\Module'                              => __DIR__ . '/Module.php',
    'Users\Controller\IndexController'          => __DIR__ . '/src/Controller/IndexController.php',
    'Users\Controller\IndexControllerFactory'   => __DIR__ . '/src/Controller/IndexControllerFactory.php',
    'Users\Entity\Users'                        => __DIR__ . '/src/Entity/Users.php',
    'Users\Service\OpenidService'               => __DIR__ . '/src/Service/OpenidService.php',
    'ZendSkeletonModuleTest\Framework\TestCase' => __DIR__ . '/tests/ZendSkeletonModule/Framework/TestCase.php',
    'ZendSkeletonModuleTest\SampleTest'         => __DIR__ . '/tests/ZendSkeletonModule/SampleTest.php',
);
