<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(

    'users/index/foo'                     => __DIR__ . '/view/users/index/foo.phtml',
    'users/index/index'                   => __DIR__ . '/view/users/index/index.phtml',
    'users/index/logout'                  => __DIR__ . '/view/users/index/logout.phtml',
    'users/index/my'                      => __DIR__ . '/view/users/index/my.phtml',
    'zend-skeleton-module/skeleton/foo'   => __DIR__ . '/view/zend-skeleton-module/skeleton/foo.phtml',
    'zend-skeleton-module/skeleton/index' => __DIR__ . '/view/zend-skeleton-module/skeleton/index.phtml',
);
