<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Cabinet\Module'                            => __DIR__ . '/Module.php',
    'Cabinet\Controller\IndexController'        => __DIR__ . '/src/Controller/SkeletonController.php',
    'ZendSkeletonModuleTest\Framework\TestCase' => __DIR__ . '/tests/ZendSkeletonModule/Framework/TestCase.php',
    'ZendSkeletonModuleTest\SampleTest'         => __DIR__ . '/tests/ZendSkeletonModule/SampleTest.php',
);
