<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(

    'cabinet/index/foo'   => __DIR__ . '/view/cabinet/index/foo.phtml',
    'cabinet/index/index' => __DIR__ . '/view/cabinet/index/index.phtml',
);
